name: Build

on:
  schedule:
#    - cron: '56 3,9,15,21 * * *'
    - cron: '0/5 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Synchronize Issues
        run: node .run/sync-issues.js ${{ secrets.TOKEN }}

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: |
          rm -rf docs
          npm run build
          mv build docs
          cp .run/CNAME docs

      - name: Deploy
        run: |
          git config --global user.name github-actions
          git config --global user.email yfr.huang@hotmail.com
          git add -A
          git commit -m "🚀 Deployed by GitHub Actions"
          git push
