name: Build

on:
  push:
    branches:
      - main
#  schedule:
#    - cron: '56 3,9,15,21 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: node .run/sync-issues.js ${{ secrets.TOKEN }}

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: sh .run/build.sh

      - name: Deploy
        run: sh .run/ci-commit-push.sh
