name: Build

on:
  schedule:
    - cron: '56 11,23 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: sh .run/build.sh

      - name: Deploy
        run: sh .run/ci-commit-push.sh
