name: Build

on:
  schedule:
    - cron: '56 11,23 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: sh .run/build.sh

      - name: Deploy
        run: |
          git config --global user.name github-actions
          git config --global user.email yfr.huang@hotmail.com
          git add -A
          git commit -m "🚀 Deployed by GitHub Actions"
          git push
